### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

### ISSUE THREAD

**Issue by flrgsr** [jiecaoyu/XNOR-Net-PyTorch#5]
Hi, 

I have run in a rather strange error.
When running your project I get the following error while attempting to read the data:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
`
This gets triggered here: https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/master/CIFAR_10/main.py#L118

Now the weird thing is that when I manually tried to load the data through ipython I get the same error when using python3 but it works fine when using python2. 

Any suggestions?Is the dataset encoded with a chinese characterset e.g?

**Comment by jiecaoyu** [comment]
Hi,

I am not sure what happens. Since I am doing all the experiment on our university server, I think it should not be a problem of Chinese characters. Could you help post the entire error message?

I guess it is due to the incompatibility with python 2 vs 3. My suggestion is to use python 2 instead.

If you don't have PyTorch installed with python 2, I think it is okay to use the dataset provided by PyTorch itself. Please check the code [here](https://github.com/kuangliu/pytorch-cifar/blob/6e59390294d96f4e72855b530786b3403bfa150e/main.py#L31) as an example of how to use trochvision.

**Comment by Rahul-RB** [comment]
I fixed this by going into data.py and replace all 'r' in the open() calls to 'rb'.

**Comment by XinDongol** [comment]
@Rahul-RB Thanks, this works for me!

**Comment by jiecaoyu** [comment]
@Rahul-RB Thanks for the solution!
