### ISSUE TITLE
details in L1 norm

### ISSUE THREAD

**Issue by ouceduxzk** [jiecaoyu/XNOR-Net-PyTorch#9]
in line 57 of util.py in MINST, you do the L1 norm for one dimension and sum up other dimension and then divide by n, which is not consistent with the paper where it treat the W as one cxhxw vector and do the L1 norm of whole vector, I am just curious why do you the former way?  because of performance or implementation reason?

Thanks, real great work

**Comment by jiecaoyu** [comment]
Hi, thanks for your question!

In the paper, the weights have a size of CxHxW. But the weights in the convolutional layer is actually NxCxHxW where C and N are the numbers of feature maps in the input and output. In this case, we will have N alphas and N corresponding binary vectors after we binarize all the weights in one convolutional layer. I calculate the N alphas with the line 57.

BTW, what I do is a simple way of calculating the L1 norm of several dimensions. Another way is to flatten the vector and calculate the L1 norm. Because PyTorch only supports calculating the L1 norm along one dimension.

**Comment by ouceduxzk** [comment]
@jiecaoyu  thanks for your explanation, I see the point now
